services:
  cardapp:
    container_name: cardapp
    build:
      context: ./backend
      dockerfile: go.Dockerfile
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/cardapp?sslmode=disable'
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
      - /app/tmp
    depends_on:
      - db

  cardapp-frontend:
    container_name: cardapp-frontend
    build:
      context: ./frontend
      dockerfile: js.Dockerfile
    ports:
      - 80:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    container_name: cardapp-db
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'cardapp'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  pgdata: {}
